<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Referral Letter - Birawa Vet</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 font-sans antialiased">
    <div class="max-w-3xl mx-auto my-10 bg-white shadow-lg rounded-lg overflow-hidden p-8">
        <div class="border-b pb-6 mb-6 flex justify-between items-center">
            <div>
                <h1 class="text-3xl font-bold text-gray-800">Birawa Vet</h1>
                <p class="text-sm text-gray-600">Professional Veterinary Services</p>
            </div>
            <div class="text-right">
                <h2 class="text-xl font-semibold text-gray-700">REFERRAL LETTER</h2>
                <p class="text-sm text-gray-500">Date: {{ $referral->created_at->format('d M Y') }}</p>
            </div>
        </div>

        <div class="grid grid-cols-2 gap-8 mb-8">
            <div>
                <h3 class="text-gray-500 text-sm uppercase font-bold tracking-wider mb-2">From:</h3>
                <p class="font-semibold">{{ $referral->sourceDoctor->name }}</p>
                <p class="text-gray-600">{{ $referral->sourceDoctor->doctorProfile->specialty ?? 'Veterinarian' }}</p>
                <p class="text-gray-600">{{ $referral->sourceDoctor->email }}</p>
            </div>
            <div>
                <h3 class="text-gray-500 text-sm uppercase font-bold tracking-wider mb-2">To:</h3>
                <p class="font-semibold">{{ $referral->target_clinic_name }}</p>
            </div>
        </div>

        <div class="bg-blue-50 p-6 rounded-lg mb-8 border-l-4 border-blue-500">
            <h3 class="text-blue-800 text-sm uppercase font-bold tracking-wider mb-4">Patient Information</h3>
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <span class="block text-xs text-gray-500 uppercase">Name</span>
                    <span class="font-medium">{{ $referral->patient->name }}</span>
                </div>
                <div>
                    <span class="block text-xs text-gray-500 uppercase">Species/Breed</span>
                    <span class="font-medium">{{ $referral->patient->species }} / {{ $referral->patient->breed }}</span>
                </div>
                <div>
                    <span class="block text-xs text-gray-500 uppercase">Owner</span>
                    <span class="font-medium">{{ $referral->patient->owners->first()->name ?? 'N/A' }}</span>
                </div>
                <div>
                    <span class="block text-xs text-gray-500 uppercase">Gender</span>
                    <span class="font-medium">{{ $referral->patient->gender }}</span>
                </div>
            </div>
        </div>

        <div class="mb-8">
            <h3 class="text-gray-800 font-bold border-b pb-2 mb-4">Clinical Notes & Reason for Referral</h3>
            <div class="text-gray-700 whitespace-pre-line leading-relaxed">
                {{ $referral->notes }}
            </div>
        </div>

        <div class="mt-12 pt-8 border-t text-center text-gray-500 text-xs">
            <p>This document is digitally generated by Birawa Vet System.</p>
            <p>Valid until: {{ $referral->valid_until->format('d M Y H:i') }} (Auto-expires in 48h)</p>
        </div>
    </div>
</body>
</html>
